### ISSUE TITLE
 GLFW emitted errors - Cannot Set Swap Interval and Failed to Make Context Current

### ISSUE THREAD

**Issue by Tomocrystal** [mushroomfire/mdapy#2]
Hello,
I am reaching out to report an issue that I have encountered while working with `mdapy` GUI. I am facing the following errors:
1. Cannot set swap interval without a current OpenGL or OpenGL ES context
2. WGL: Failed to make context current: ......
I would like to kindly request your assistance in resolving these errors. Thank you for your attention to this matter. I look forward to hearing from you soon.

**Comment by mushroomfire** [comment]
@Tomocrystal Hi, please give me more information, including your OS information, python/mdapy version. A simple example code is also helpful to reproduce the error.

**Comment by Tomocrystal** [comment]
![image](https://github.com/mushroomfire/mdapy/assets/161665779/2d12e84c-6852-414e-8298-83ec87672d98)
I started to run the GUI mode of **mdapy**  in CMD, then the errors kept popping up as shown in the image.
_OS: win10
python:3.10.14
mdapy:0.10.4_

**Comment by mushroomfire** [comment]
@Tomocrystal It seems not to be a mdapy API bug, and maybe a GLFW bug. You can try to explicitly allow Python to use the Nvidia GPU. The integrated Intel GPU may do not work.
![image](https://github.com/mushroomfire/mdapy/assets/77276727/1ed3b496-f5d1-4547-9ac9-62482f765374)
![image](https://github.com/mushroomfire/mdapy/assets/77276727/d15cb8b4-fe2a-4891-aeb6-edf313b9c899)

**Comment by Tomocrystal** [comment]
The solution you provided worked perfectly and resolved the issue. Thank you so much for your help!
