### ISSUE TITLE
Whether the mdapy can be used to calculate the vibrational dos based on the dump file of lammps?

### ISSUE THREAD

**Issue by Guancred** [mushroomfire/mdapy#3]
Hi,
Whether the mdapy can be used to calculate the vibrational dos based on the dump file of lammps? And which functional can be used?

Thanks very much
Hong

**Comment by mushroomfire** [comment]
Hi, @Guancred 
The mdapy library does not currently include the feature mentioned. Due to my limited understanding of the VDOS mechanism, I do not have any immediate plans to implement it. You may find the information in [this link](https://zenodo.org/records/5261318) beneficial for your needs.

**Comment by Guancred** [comment]
> Hi, @Guancred The mdapy library does not currently include the feature mentioned. Due to my limited understanding of the VDOS mechanism, I do not have any immediate plans to implement it. You may find the information in [this link](https://zenodo.org/records/5261318) beneficial for your needs.

Thanks, it's very helpful.
