### ISSUE TITLE
About the trajectory analysis

### ISSUE THREAD

**Issue by Sacho2020** [mushroomfire/mdapy#6]
Hi,

I would like to know whether the current version supports the analysis of multiple atomic configurations in the  trajectory? 

I found that it is unable to load all atomic configurations of a trajectory, and only recognizes the box information of first atomic configuration, including xyz and dump files., and it also shows the error "found more fields than defined in 'Schema'" for the loading of trajectory data in xyz format.

Sacho

**Comment by mushroomfire** [comment]
Hi, @Sacho2020 . Mdapy is mainly designed for analyzing single frame. While you can split the trajectory by mp.split_xyz() into separate frames, and then you can read them by mp.System or mp.MultiSystem, and do what you want to do.
